Fix exception in write_cmdlines (#2510)
Fixes an exception thrown from write_cmdlines if a difftest fails:

```
NameError: name 'config' is not defined. Did you mean: 'Config'?
```

The regression was introduced in commit
3e17997fd8523ee042707dd1a53172bd560b1951