Fix: Add missing sys/types.h include for ssize_t (#3161)
The build is failing on musl, <cstdlib> is not covering it. So
explicitly adding a <sys/types.h>

> third_party/perfetto/include/perfetto/ext/base/small_set.h:54:40:
error: unknown type name 'ssize_t'; did you mean 'size_t'?
>    54 |     return arr_.cbegin() + static_cast<ssize_t>(filled_);
>       |                                        ^~~~~~~
>       |                                        size_t
>
third_party/unsupported_toolchains/castlite/common/llvm-clang/usr/lib/clang/19/include/__stddef_size_t.h:18:23:
note: 'size_t' declared here
>    18 | typedef __SIZE_TYPE__ size_t;
>       |                       ^
> 1 error generated.
>

Signed-off-by: Volodymyr Riazantsev <riazantsevv@google.com>