Revert "tp: Parse tz offset from alarm dumpsys"
This reverts commit d43142ce4c12d55c6347233b3a36333e99f68f72.

Reason for revert: This is failing on Windows with the error:
```
[23073/121573] CXX obj/third_party/perfetto/src/trace_processor/importers/android_bugreport/android_bugreport/android_dumpstate_reader.obj
../../third_party/llvm-build/Release+Asserts/bin/clang-cl.exe /c ../../third_party/perfetto/src/trace_processor/importers/android_bugreport/an...(too long)
../../third_party/perfetto/src/trace_processor/importers/android_bugreport/android_dumpstate_reader.cc(186,33): error: use of undeclared identifier 'timegm'
  186 |     int64_t tz_adjusted_ts_ms = timegm(&time_struct) * 1000ll;
```

See https://chromium-review.googlesource.com/c/chromium/src/+/6178560?tab=checks

Change-Id: I1b207f47fc300db58f84488801f8268a6b5710ff