Move NewTrace down to fix incomplete type error
After upgrading libc++, clang generates this error:

error: invalid application of 'sizeof' to an incomplete type 'perfetto::TracingSession'

Moving the function shouldn't prevent it from being inlined, because it
is still marked with __attribute__((__always_inline__)).

Bug: 175635923
Test: m MODULES-IN-external-perfetto
Change-Id: Icce55c5563938faf9881bcea177c0b22f324c244