Add static for MSVC /permissive-
This static was added there for MSVC with
f43e650a081b("sdk: Make the tracing SDK compatible with MSVC")
in order to make it build with MSVC with the `/permissive-` flag.

It was removed with
bb9298ff4d2b("Remove static qualifier from kCatIndex")
in order to reduce binary size on android.

This commit adds an ifdef to support both.

The problem only appears with MSVC `/permissive-` flag with a
TRACE_EVENT macro inside a lambda.

It's sad that we have to do this, but:
* This code is overly complicated.
* There is probably an MSVC compiler bug.

The MSVC bug can be reproduced with this minified repro:

```
// Compile with
//
// "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\cl.exe" /c /permissive- msvcbug.cc
int main(int, const char**) {
  [&] {
    struct A {
      A(int) {}
    } a{[&] {
      constexpr int XXX = 1;
      return XXX;
    }()};
  }();

  return 0;
}
```

```
Microsoft (R) C/C++ Optimizing Compiler Version 19.41.34123 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

msvcbug.cc
msvcbug.cc(12): error C2065: 'XXX': undeclared identifier
```

Fixes: https://github.com/google/perfetto/issues/986
Change-Id: I201cf369a96e6a8636ac3dddc43d3ca226df20f6