ui: Catch and ignore cache errors
Ignore:
UnknownError: Unexpected internal error. {}
since it is not very actionable.

Bug: 227785665
Change-Id: Ib0332ce0c2aeeb9e4308108a0f007bbc6832dea2