ci: fix PyJWT failure caused by rebuilding frontend
Fixes the stack:
```
TypeError: Issuer (iss) must be a string.

at .encode ( /layers/google.python.pip/pip/lib/python3.12/site-packages/jwt/api_jwt.py:139 )
at .get_github_installation_token ( /srv/common_utils.py:76 )
at .get_cached_github_token ( /srv/main.py:62 )
```