TrackEvent: GCC compatibility fix for using track events in templates
This patch fixes an issue where GCC is unable to compile track events
that are used inside templated functions. The failure is not being able
to use a constexpr value as the template argument for
TrackEventRegistry::Validate(). As a workaround, we turn the category
index from a template argument to Validate() into a regular parameter.
The downside is that we can no longer use static_assert to validate the
category name, so instead on validation failure we call a non-constexpr
function, which will fail the build.

Example error when specifying an invalid category:

=== GCC (much better than Clang in this case) ===

../../include/perfetto/tracing/track_event_category_registry.h:281:6: error: call to non-‘constexpr’ function ‘perfetto::internal::TrackEventCategoryRegistry::CheckIsValidCategoryIndex(size_t)::<lambda()>’
  276 |     return index != kInvalidCategoryIndex ? index : [] {
      |                                                     ~~~~
  277 |       PERFETTO_CHECK(!
      |       ~~~~~~~~~~~~~~~~
  278 |           "A track event used an unknown category. Please add it to "
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  279 |           "PERFETTO_DEFINE_CATEGORIES().");
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  280 |       return 0u;
      |       ~~~~~~~~~~
  281 |     }();
      |     ~^~
../../include/perfetto/tracing/track_event_category_registry.h:276:53: note: ‘perfetto::internal::TrackEventCategoryRegistry::CheckIsValidCategoryIndex(size_t)::<lambda()>’ is not usable as a ‘constexpr’ function because:
  276 |     return index != kInvalidCategoryIndex ? index : [] {
      |                                                     ^
../../include/perfetto/tracing/track_event_category_registry.h:276:53: note: lambdas are implicitly ‘constexpr’ only in C++17 and later
In file included from ../../include/perfetto/tracing/track_event.h:23,
                 from ../../include/perfetto/tracing.h:34,
                 from ../../src/tracing/test/api_integrationtest.cc:30:
../../src/tracing/test/api_integrationtest.cc: In lambda function:
../../src/tracing/test/api_integrationtest.cc:678:3: error: no matching function for call to ‘perfetto::TrackEvent::TraceForCategory<kCatIndex678>(uint32_t&, const char [6], const char [10], const Type&)’
  678 |   TRACE_EVENT_BEGIN("xtest", "TestEvent");

=== Clang ===

../../src/tracing/test/api_integrationtest.cc:678:3: error: constexpr variable 'kCatIndex678' must be initialized by a constant expression
  TRACE_EVENT_BEGIN("xtest", "TestEvent");
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../include/perfetto/tracing/track_event.h:207:3: note: expanded from macro 'TRACE_EVENT_BEGIN'
  PERFETTO_INTERNAL_TRACK_EVENT(               \
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../include/perfetto/tracing/internal/track_event_macros.h:106:20: note: expanded from macro 'PERFETTO_INTERNAL_TRACK_EVENT'
    constexpr auto PERFETTO_UID(kCatIndex) =                              \
                   ^
../../include/perfetto/tracing/internal/track_event_macros.h:97:30: note: expanded from macro 'PERFETTO_UID'
                             ^
../../include/perfetto/tracing/internal/track_event_macros.h:96:40: note: expanded from macro 'PERFETTO_INTERNAL_CONCAT'
                                       ^
../../include/perfetto/tracing/internal/track_event_macros.h:95:41: note: expanded from macro 'PERFETTO_INTERNAL_CONCAT2'
                                        ^
<scratch space>:73:1: note: expanded from here
kCatIndex678
^
../../include/perfetto/tracing/track_event_category_registry.h:274:75: note: non-literal type '(lambda at ../../include/perfetto/tracing/track_event_category_registry.h:274:75)' cannot be used in a constant expression
        /* Invalid category -- add it to PERFETTO_DEFINE_CATEGORIES(). */ [] {

Bug: 148779455
Change-Id: Ibb829577743ffca56294af7b1b193a456a0c0744