Normalize path separators in fix_include_guards (#2889)
This change ensures that file paths in fix_include_guards use `/` path
separators.

On Windows, `os.path.join` results in a path separated by backslashes,
which causes the script to fail its asserts on files intended to be
excluded (because the paths don't match those in the `EXCLUDED_FILES`
list, which uses forward slashes).

Without this change, on Windows:
```
PS C:\src\perfetto> python3 tools/fix_include_guards
Traceback (most recent call last):
  File "C:\src\perfetto\tools\fix_include_guards", line 92, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\src\perfetto\tools\fix_include_guards", line 84, in main
    num_files_changed += fix_guards(fpath, checkonly)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\perfetto\tools\fix_include_guards", line 47, in fix_guards
    assert endif_line_idx > 0, fpath
           ^^^^^^^^^^^^^^^^^^
AssertionError: src\trace_processor\perfetto_sql\grammar\perfettosql_grammar.h
```

With this change:
```
PS C:\src\perfetto> python3 tools/fix_include_guards                                                                                                                                                               
0 files changed
```