UI: add src/test/diff_viewer to .eslintignore. Also fix PRESUBMIT.py
It was causing a warning from ./format-sources --all
becasue eslint complains that the folder is excluded by tsconfig
but included in eslint.
Also fix a small bug in PRESUBMIT.py which would cause an error
if the presubmit took more than 3 seconds:
  File "/Users/primiano/code/perfetto/PRESUBMIT.py", line 31, in RunAndReportIfLong
    print("{} took >{:.2}s ({:.2}s)".format(name, limit, runtime))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ValueError: Precision not allowed in integer format specifier
Change-Id: I21e3e7700895a613400bdbad64cee426f41e1a3c