Fix build error due to missing cstdint with gcc-15
  * Add missing cstdint include to fix build error with gcc-15

  * To fix the error with gcc-15.
  http://errors.yoctoproject.org/Errors/Details/851189/
    ../git/include/perfetto/ext/tracing/core/slice.h:47:46: error: 'uint8_t' was not declared in this scope
    47 |   static Slice TakeOwnership(std::unique_ptr<uint8_t[]> buf, size_t size) {
        |                                              ^~~~~~~
    ../git/include/perfetto/ext/tracing/core/slice.h:25:1: note: 'uint8_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
    24 | #include <string>
    +++ |+#include <cstdint>

  * See also: https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes
  Some C++ Standard Library headers have been changed to no longer include
  other headers that were being used internally by the library.

Signed-off-by: mark.yang <mark.yang@lge.com>
Signed-off-by: markyang92 <pllpokko@alumni.kaist.ac.kr>