Revert "tp: Fix ToAbsTime time zone issue."
This reverts commit bf0d85a0776e812e67c1f35f5350ecca5cbd074a.

Reason for revert: Breaks Chromium build Perfetto autoroller because this doesn't compile on Windows.

See error: [296/5350] CXX obj/third_party/perfetto/src/trace_processor/importers/common/common/clock_converter.obj
FAILED: obj/third_party/perfetto/src/trace_processor/importers/common/common/clock_converter.obj
..\..\buildtools\reclient\rewrapper -cfg=..\..\buildtools\reclient_cfgs\chromium-browser-clang\rewra...(too long)
../../third_party/perfetto/src/trace_processor/importers/common/clock_converter.cc(56,59): error: no member named 'tm_gmtoff' in 'tm'
56 |     timezone_offset_s_ = static_cast<int32_t>(local_time->tm_gmtoff);
|                                               ~~~~~~~~~~  ^
1 error generated.
(cherry picked from https://android-review.googlesource.com/q/commit:0287014eab13af5ff1f07f9190d432e22b83b43b)
Merged-In: I06a76548f8c098f27a78c039bd98239bb6bd3421
Change-Id: I06a76548f8c098f27a78c039bd98239bb6bd3421