test: Fix Android in-tree build wrt perfetto_flags_c_lib (#2339)
It is broken since 8a5825d4a6f8("tp: use MurmurHash for
base::FlatHashMap behind a flag (#2290)", with errors like:

```
FAILED: out/soong/.intermediates/external/perfetto/test/cts/reporter/CtsPerfettoReporterTestCases/android_x86_x86_64/obj/external/perfetto/test/cts/reporter/reporter_test_cts.o
...external/perfetto/test/cts/reporter/CtsPerfettoReporterTestCases/android_x86_x86_64/obj/external/perfetto/test/cts/reporter/reporter_test_cts.o external/perfetto/test/cts/reporter/reporter_test_cts.cc
In file included from external/perfetto/test/cts/reporter/reporter_test_cts.cc:26:
In file included from external/perfetto/test/test_helper.h:46:
In file included from external/perfetto/src/traced/probes/probes_producer.h:31:
In file included from external/perfetto/src/traced/probes/ftrace/ftrace_controller.h:33:
In file included from external/perfetto/src/traced/probes/ftrace/cpu_reader.h:27:
In file included from external/perfetto/include/perfetto/ext/base/flat_hash_map.h:21:
external/perfetto/include/perfetto/ext/base/flags.h:24:10: fatal error: 'perfetto_flags.h' file not found
   24 | #include <perfetto_flags.h>
      |          ^~~~~~~~~~~~~~~~~~
1 error generated.
```

Tested: `cd external/perfetto; mm`