Fix build with the latest libc++
The latest libc++ no longer transitively include cstdlib, causing a
build failure.

In file included from external/perfetto/src/profiling/common/profiler_guardrails.cc:17:
In file included from external/perfetto/src/profiling/common/profiler_guardrails.h:29:
external/perfetto/src/profiling/common/proc_utils.h:50:20: error: use of undeclared identifier 'strtol'
   50 |     long int pid = strtol(entry->d_name, &end, 10);
      |