Use os.replace instead of os.rename (#3009)
Perfetto's scripts use `os.rename` to replace files with new versions.
However, `os.rename` fails on Windows when the destination file exists.

`os.replace` is equivalent to `os.rename` on POSIX, and on Windows
allows replacing an existing file (see
[docs](https://docs.python.org/3/library/os.html#os.rename)). This
change replaces uses of `os.rename` with `os.replace`, because the
scripts don't seem like they intend to fail if the file already exists.

This fixes the following error on Windows:
```
PS C:\src\perfetto> python3 tools/gen_all out/default
Running python3 tools\check_include_violations
Running python3 tools\check_proto_comments
Running python3 tools\fix_include_guards
0 files changed
Running python3 tools\gen_merged_protos
Running python3 tools\gen_amalgamated_python_tools
INFO    : Amalgamating python/tools/record_android_trace.py -> tools/record_android_trace
Traceback (most recent call last):
  File "C:\src\perfetto\tools\gen_amalgamated_python_tools", line 123, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\src\perfetto\tools\gen_amalgamated_python_tools", line 118, in main
    success = success and amalgamate(src, dst, check_only)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\perfetto\tools\gen_amalgamated_python_tools", line 106, in amalgamate
    os.rename(dst + '.tmp', dst)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'tools/record_android_trace.tmp' -> 'tools/record_android_trace'
Error: Command: python3 tools\gen_amalgamated_python_tools failed
```